### ISSUE TITLE
Doesn't discard blocks with comments

### ISSUE THREAD

**Issue by ismay** [ben-eb/postcss-discard-empty#1]
Was wondering whether this is intentional. I'd say that it's safe to discard them, as currently I have `:root` blocks that remain in the css after `postcss-custom-properties` has processed them.

```css
/* this shows up in the output: */
:root {
  /* with some comments */
}
```

**Comment by ismay** [comment]
Nevermind, I should have checked the tests. Can see that it shouldn't be responsible for discarding comments, so it's intentional. https://github.com/ben-eb/postcss-discard-comments can do that.

**Comment by ben-eb** [comment]
Yeah. There's a lot of overlap with these modules, but I think it's better to have fewer responsibilities than many. :smile:

**Comment by ismay** [comment]
I agree, keeps the code clean and the functionality clear. :)
